using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using EnvSync.Core.Model;

namespace EnvSync.Core.CodeGeneration;

/// <summary>
/// Generates strongly-typed source files from an environment schema.
/// </summary>
public sealed class BindingGenerator
{
    /// <summary>
    /// Generates a typed binding file for the requested language.
    /// </summary>
    /// <param name="schema">The schema to generate bindings from.</param>
    /// <param name="language">The binding language to generate.</param>
    /// <param name="rootName">The generated root type or interface name.</param>
    /// <param name="scope">The optional C# namespace. Ignored for TypeScript generation.</param>
    /// <returns>The generated binding file.</returns>
    public GeneratedBindingFile Generate(EnvSchema schema, BindingLanguage language, string rootName = "EnvSyncEnvironment", string? scope = null)
    {
        ArgumentNullException.ThrowIfNull(schema);
        ArgumentException.ThrowIfNullOrWhiteSpace(rootName);

        return language switch
        {
            BindingLanguage.TypeScript => new GeneratedBindingFile("envsync.generated.ts", GenerateTypeScript(schema, rootName)),
            BindingLanguage.CSharp => new GeneratedBindingFile("EnvSyncEnvironment.g.cs", GenerateCSharp(schema, rootName, scope ?? "EnvSync.Generated")),
            _ => throw new ArgumentOutOfRangeException(nameof(language), language, "Unsupported binding language."),
        };
    }

    private static string GenerateTypeScript(EnvSchema schema, string interfaceName)
    {
        EnsureValidTypeScriptIdentifier(interfaceName, "TypeScript interface name");
        var propertyNames = BuildIdentifierMap(schema, IdentifierNameHelper.ToCamelCase, "TypeScript");

        var lines = new List<string>
        {
            "// <auto-generated />",
            string.Empty,
            "export const envKeys = {",
        };

        foreach (var definition in schema.Definitions)
        {
            lines.Add($"  {propertyNames[definition.Name]}: {ToTypeScriptString(definition.Name)},");
        }

        lines.Add("} as const;");
        lines.Add(string.Empty);
        lines.Add($"export interface {interfaceName} {{");

        foreach (var definition in schema.Definitions)
        {
            if (!string.IsNullOrWhiteSpace(definition.Description))
            {
                lines.Add($"  /** {definition.Description} */");
            }

            var optionalSuffix = definition.IsOptionalWithoutDefault ? "?" : string.Empty;
            lines.Add($"  {propertyNames[definition.Name]}{optionalSuffix}: {GetTypeScriptType(definition)};");
        }

        lines.Add("}");
        return string.Join(Environment.NewLine, lines) + Environment.NewLine;
    }

    private static string GenerateCSharp(EnvSchema schema, string typeName, string @namespace)
    {
        EnsureValidCSharpIdentifier(typeName, "C# type name");
        EnsureValidCSharpNamespace(@namespace);
        var propertyNames = BuildIdentifierMap(schema, IdentifierNameHelper.ToPascalCase, "C#");

        var lines = new List<string>
        {
            "// <auto-generated />",
            string.Empty,
            $"namespace {@namespace};",
            string.Empty,
            "public static class EnvKeys",
            "{",
        };

        foreach (var definition in schema.Definitions)
        {
            lines.Add($"    public const string {propertyNames[definition.Name]} = {ToCSharpStringLiteral(definition.Name)};");
        }

        lines.Add("}");
        lines.Add(string.Empty);
        lines.Add($"public sealed class {typeName}");
        lines.Add("{");

        foreach (var definition in schema.Definitions)
        {
            if (!string.IsNullOrWhiteSpace(definition.Description))
            {
                lines.Add($"    /// <summary>{definition.Description}</summary>");
            }

            var propertyName = propertyNames[definition.Name];
            var propertyType = GetCSharpType(definition);
            var defaultValue = GetCSharpDefaultValue(definition);

            if (definition.Required && !definition.HasDefault)
            {
                lines.Add($"    public required {propertyType} {propertyName} {{ get; init; }}");
            }
            else if (defaultValue is not null)
            {
                lines.Add($"    public {propertyType} {propertyName} {{ get; init; }} = {defaultValue};");
            }
            else
            {
                lines.Add($"    public {propertyType} {propertyName} {{ get; init; }}");
            }
        }

        lines.Add("}");
        return string.Join(Environment.NewLine, lines) + Environment.NewLine;
    }

    private static string GetTypeScriptType(EnvVariableDefinition definition)
    {
        if (definition.AllowedValues.Count > 0)
        {
            return string.Join(" | ", definition.AllowedValues.Select(ToTypeScriptString));
        }

        return definition.Type switch
        {
            EnvValueType.String => "string",
            EnvValueType.Number => "number",
            EnvValueType.Boolean => "boolean",
            _ => throw new ArgumentOutOfRangeException(nameof(definition.Type), definition.Type, "Unsupported environment value type."),
        };
    }

    private static string GetCSharpType(EnvVariableDefinition definition)
    {
        var baseType = definition.Type switch
        {
            EnvValueType.String => "string",
            EnvValueType.Number => "double",
            EnvValueType.Boolean => "bool",
            _ => throw new ArgumentOutOfRangeException(nameof(definition.Type), definition.Type, "Unsupported environment value type."),
        };

        if (definition.Required || definition.HasDefault)
        {
            return baseType;
        }

        return baseType == "string" ? "string?" : $"{baseType}?";
    }

    private static string? GetCSharpDefaultValue(EnvVariableDefinition definition)
    {
        if (!definition.HasDefault)
        {
            return null;
        }

        return definition.Type switch
        {
            EnvValueType.String => ToCSharpStringLiteral(definition.DefaultValue!),
            EnvValueType.Number => definition.DefaultValue,
            EnvValueType.Boolean => definition.DefaultValue,
            _ => throw new ArgumentOutOfRangeException(nameof(definition.Type), definition.Type, "Unsupported environment value type."),
        };
    }

    private static IReadOnlyDictionary<string, string> BuildIdentifierMap(
        EnvSchema schema,
        Func<string, string> convert,
        string language)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        var seen = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var definition in schema.Definitions)
        {
            var identifier = convert(definition.Name);
            if (!IdentifierNameHelper.IsValidIdentifier(identifier))
            {
                throw new ArgumentException($"Schema variable '{definition.Name}' generated invalid {language} identifier '{identifier}'.");
            }

            if (seen.TryGetValue(identifier, out var existingKey))
            {
                throw new ArgumentException(
                    $"Schema variables '{existingKey}' and '{definition.Name}' both generate {language} identifier '{identifier}'.");
            }

            seen[identifier] = definition.Name;
            result[definition.Name] = identifier;
        }

        return result;
    }

    private static void EnsureValidTypeScriptIdentifier(string value, string description)
    {
        if (!IdentifierNameHelper.IsValidIdentifier(value) || TypeScriptKeywords.Contains(value))
        {
            throw new ArgumentException($"{description} '{value}' is not a valid identifier.", nameof(value));
        }
    }

    private static void EnsureValidCSharpIdentifier(string value, string description)
    {
        if (!IdentifierNameHelper.IsValidIdentifier(value) || CSharpKeywords.Contains(value))
        {
            throw new ArgumentException($"{description} '{value}' is not a valid identifier.", nameof(value));
        }
    }

    private static void EnsureValidCSharpNamespace(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);

        foreach (var segment in value.Split('.'))
        {
            if (!IdentifierNameHelper.IsValidIdentifier(segment) || CSharpKeywords.Contains(segment))
            {
                throw new ArgumentException($"C# namespace '{value}' contains invalid segment '{segment}'.", nameof(value));
            }
        }
    }

    private static string ToTypeScriptString(string value) => JsonSerializer.Serialize(value, TypeScriptJsonOptions);

    private static string ToCSharpStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');

        foreach (var character in value)
        {
            _ = character switch
            {
                '\\' => builder.Append("\\\\"),
                '"' => builder.Append("\\\""),
                '\0' => builder.Append("\\0"),
                '\a' => builder.Append("\\a"),
                '\b' => builder.Append("\\b"),
                '\f' => builder.Append("\\f"),
                '\n' => builder.Append("\\n"),
                '\r' => builder.Append("\\r"),
                '\t' => builder.Append("\\t"),
                '\v' => builder.Append("\\v"),
                < ' ' => builder.Append("\\u").Append(((int)character).ToString("X4")),
                _ => builder.Append(character),
            };
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static readonly HashSet<string> TypeScriptKeywords = new(StringComparer.Ordinal)
    {
        // ECMAScript reserved words
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "debugger",
        "default",
        "delete",
        "do",
        "else",
        "enum",
        "export",
        "extends",
        "false",
        "finally",
        "for",
        "function",
        "if",
        "import",
        "in",
        "instanceof",
        "new",
        "null",
        "return",
        "super",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "var",
        "void",
        "while",
        "with",
        // ECMAScript strict-mode future reserved words
        "as",
        "implements",
        "interface",
        "let",
        "package",
        "private",
        "protected",
        "public",
        "static",
        "yield",
        // TypeScript-specific keywords that would produce invalid output as identifiers
        "abstract",
        "any",
        "asserts",
        "assert",
        "bigint",
        "boolean",
        "constructor",
        "declare",
        "get",
        "infer",
        "intrinsic",
        "is",
        "keyof",
        "module",
        "namespace",
        "never",
        "number",
        "object",
        "of",
        "out",
        "override",
        "readonly",
        "require",
        "satisfies",
        "set",
        "string",
        "symbol",
        "type",
        "undefined",
        "unique",
        "unknown",
        "using",
        "from",
        "global",
    };

    private static readonly JsonSerializerOptions TypeScriptJsonOptions = new()
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract",
        "as",
        "base",
        "bool",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "checked",
        "class",
        "const",
        "continue",
        "decimal",
        "default",
        "delegate",
        "do",
        "double",
        "else",
        "enum",
        "event",
        "explicit",
        "extern",
        "false",
        "finally",
        "fixed",
        "float",
        "for",
        "foreach",
        "goto",
        "if",
        "implicit",
        "in",
        "int",
        "interface",
        "internal",
        "is",
        "lock",
        "long",
        "namespace",
        "new",
        "null",
        "object",
        "operator",
        "out",
        "override",
        "params",
        "private",
        "protected",
        "public",
        "readonly",
        "ref",
        "return",
        "sbyte",
        "sealed",
        "short",
        "sizeof",
        "stackalloc",
        "static",
        "string",
        "struct",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "uint",
        "ulong",
        "unchecked",
        "unsafe",
        "ushort",
        "using",
        "virtual",
        "void",
        "volatile",
        "while",
    };
}
